# Generated by Django 3.0.1 on 2020-01-04 04:33

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_activity',
            field=models.DateTimeField(default=timezone.now, verbose_name='Last activity date'),
        ),
        migrations.AddField(
            model_name='room',
            name='timestamp',
            field=models.DateTimeField(default=timezone.now, verbose_name='Creation Date'),
        ),
    ]
